project_id = "kduahnbixkdjzfcjqfpb"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-audit-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
